name = "buddy-companion"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGIN = "*"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "d34dbbda7ca14fc5aedcbacd36a5d38d"

[triggers]
crons = ["*/30 * * * *"]
